// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: adapters/controllers/grpc/media.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaOrder int32

const (
	MediaOrder_MEDIA_ORDER_ASC  MediaOrder = 0
	MediaOrder_MEDIA_ORDER_DESC MediaOrder = 1
)

// Enum value maps for MediaOrder.
var (
	MediaOrder_name = map[int32]string{
		0: "MEDIA_ORDER_ASC",
		1: "MEDIA_ORDER_DESC",
	}
	MediaOrder_value = map[string]int32{
		"MEDIA_ORDER_ASC":  0,
		"MEDIA_ORDER_DESC": 1,
	}
)

func (x MediaOrder) Enum() *MediaOrder {
	p := new(MediaOrder)
	*p = x
	return p
}

func (x MediaOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_adapters_controllers_grpc_media_proto_enumTypes[0].Descriptor()
}

func (MediaOrder) Type() protoreflect.EnumType {
	return &file_adapters_controllers_grpc_media_proto_enumTypes[0]
}

func (x MediaOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaOrder.Descriptor instead.
func (MediaOrder) EnumDescriptor() ([]byte, []int) {
	return file_adapters_controllers_grpc_media_proto_rawDescGZIP(), []int{0}
}

type Media struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attributes    *structpb.Struct `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Height        float64          `protobuf:"fixed64,3,opt,name=height,proto3" json:"height,omitempty"`
	Width         float64          `protobuf:"fixed64,4,opt,name=width,proto3" json:"width,omitempty"`
	X             float64          `protobuf:"fixed64,5,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64          `protobuf:"fixed64,6,opt,name=y,proto3" json:"y,omitempty"`
	Url           string           `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Phash         string           `protobuf:"bytes,8,opt,name=phash,proto3" json:"phash,omitempty"`
	Filename      string           `protobuf:"bytes,9,opt,name=filename,proto3" json:"filename,omitempty"`
	MediaUrl      string           `protobuf:"bytes,10,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	ScreenshotUrl string           `protobuf:"bytes,11,opt,name=screenshot_url,json=screenshotUrl,proto3" json:"screenshot_url,omitempty"`
	ResourceUrl   string           `protobuf:"bytes,12,opt,name=resource_url,json=resourceUrl,proto3" json:"resource_url,omitempty"`
	TaskId        string           `protobuf:"bytes,13,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CreatedAt     string           `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string           `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string           `protobuf:"bytes,16,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *Media) Reset() {
	*x = Media{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adapters_controllers_grpc_media_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_controllers_grpc_media_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_adapters_controllers_grpc_media_proto_rawDescGZIP(), []int{0}
}

func (x *Media) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Media) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Media) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Media) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Media) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Media) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Media) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Media) GetPhash() string {
	if x != nil {
		return x.Phash
	}
	return ""
}

func (x *Media) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Media) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *Media) GetScreenshotUrl() string {
	if x != nil {
		return x.ScreenshotUrl
	}
	return ""
}

func (x *Media) GetResourceUrl() string {
	if x != nil {
		return x.ResourceUrl
	}
	return ""
}

func (x *Media) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Media) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Media) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Media) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type MediaIdParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MediaIdParam) Reset() {
	*x = MediaIdParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adapters_controllers_grpc_media_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaIdParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaIdParam) ProtoMessage() {}

func (x *MediaIdParam) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_controllers_grpc_media_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaIdParam.ProtoReflect.Descriptor instead.
func (*MediaIdParam) Descriptor() ([]byte, []int) {
	return file_adapters_controllers_grpc_media_proto_rawDescGZIP(), []int{1}
}

func (x *MediaIdParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MediaHashParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phash string `protobuf:"bytes,1,opt,name=phash,proto3" json:"phash,omitempty"`
}

func (x *MediaHashParam) Reset() {
	*x = MediaHashParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adapters_controllers_grpc_media_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaHashParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaHashParam) ProtoMessage() {}

func (x *MediaHashParam) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_controllers_grpc_media_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaHashParam.ProtoReflect.Descriptor instead.
func (*MediaHashParam) Descriptor() ([]byte, []int) {
	return file_adapters_controllers_grpc_media_proto_rawDescGZIP(), []int{2}
}

func (x *MediaHashParam) GetPhash() string {
	if x != nil {
		return x.Phash
	}
	return ""
}

type MediaFiltersParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash      *string     `protobuf:"bytes,1,opt,name=hash,proto3,oneof" json:"hash,omitempty"`
	CreatedAt *string     `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	TaskId    *string     `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`
	Order     *MediaOrder `protobuf:"varint,4,opt,name=order,proto3,enum=grpc.MediaOrder,oneof" json:"order,omitempty"`
	Limit     *int32      `protobuf:"varint,5,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
}

func (x *MediaFiltersParam) Reset() {
	*x = MediaFiltersParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adapters_controllers_grpc_media_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaFiltersParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaFiltersParam) ProtoMessage() {}

func (x *MediaFiltersParam) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_controllers_grpc_media_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaFiltersParam.ProtoReflect.Descriptor instead.
func (*MediaFiltersParam) Descriptor() ([]byte, []int) {
	return file_adapters_controllers_grpc_media_proto_rawDescGZIP(), []int{3}
}

func (x *MediaFiltersParam) GetHash() string {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return ""
}

func (x *MediaFiltersParam) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *MediaFiltersParam) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *MediaFiltersParam) GetOrder() MediaOrder {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return MediaOrder_MEDIA_ORDER_ASC
}

func (x *MediaFiltersParam) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type MediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Media *Media `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
}

func (x *MediaResponse) Reset() {
	*x = MediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adapters_controllers_grpc_media_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaResponse) ProtoMessage() {}

func (x *MediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_controllers_grpc_media_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaResponse.ProtoReflect.Descriptor instead.
func (*MediaResponse) Descriptor() ([]byte, []int) {
	return file_adapters_controllers_grpc_media_proto_rawDescGZIP(), []int{4}
}

func (x *MediaResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type MediaListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Media []*Media `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
}

func (x *MediaListResponse) Reset() {
	*x = MediaListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adapters_controllers_grpc_media_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaListResponse) ProtoMessage() {}

func (x *MediaListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_controllers_grpc_media_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaListResponse.ProtoReflect.Descriptor instead.
func (*MediaListResponse) Descriptor() ([]byte, []int) {
	return file_adapters_controllers_grpc_media_proto_rawDescGZIP(), []int{5}
}

func (x *MediaListResponse) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

var File_adapters_controllers_grpc_media_proto protoreflect.FileDescriptor

var file_adapters_controllers_grpc_media_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x03, 0x0a, 0x05,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x68,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x55, 0x72, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x63, 0x72,
	0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x55, 0x72, 0x6c,
	0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x1e, 0x0a, 0x0c, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x49, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x0e, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x48, 0x61, 0x73, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73,
	0x68, 0x22, 0xee, 0x01, 0x0a, 0x11, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x17, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x88, 0x01, 0x01,
	0x12, 0x22, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x2b, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x48, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12,
	0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x04,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x68,
	0x61, 0x73, 0x68, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x22, 0x32, 0x0a, 0x0d, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52,
	0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x22, 0x36, 0x0a, 0x11, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2a, 0x37,
	0x0a, 0x0a, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x13, 0x0a, 0x0f,
	0x4d, 0x45, 0x44, 0x49, 0x41, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x41, 0x53, 0x43, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52,
	0x5f, 0x44, 0x45, 0x53, 0x43, 0x10, 0x01, 0x32, 0xcc, 0x01, 0x0a, 0x0c, 0x4d, 0x65, 0x64, 0x69,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x42, 0x79, 0x49, 0x64, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x13, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x42,
	0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x48, 0x61, 0x73, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x13, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x42, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x17, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_adapters_controllers_grpc_media_proto_rawDescOnce sync.Once
	file_adapters_controllers_grpc_media_proto_rawDescData = file_adapters_controllers_grpc_media_proto_rawDesc
)

func file_adapters_controllers_grpc_media_proto_rawDescGZIP() []byte {
	file_adapters_controllers_grpc_media_proto_rawDescOnce.Do(func() {
		file_adapters_controllers_grpc_media_proto_rawDescData = protoimpl.X.CompressGZIP(file_adapters_controllers_grpc_media_proto_rawDescData)
	})
	return file_adapters_controllers_grpc_media_proto_rawDescData
}

var file_adapters_controllers_grpc_media_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_adapters_controllers_grpc_media_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_adapters_controllers_grpc_media_proto_goTypes = []interface{}{
	(MediaOrder)(0),           // 0: grpc.MediaOrder
	(*Media)(nil),             // 1: grpc.Media
	(*MediaIdParam)(nil),      // 2: grpc.MediaIdParam
	(*MediaHashParam)(nil),    // 3: grpc.MediaHashParam
	(*MediaFiltersParam)(nil), // 4: grpc.MediaFiltersParam
	(*MediaResponse)(nil),     // 5: grpc.MediaResponse
	(*MediaListResponse)(nil), // 6: grpc.MediaListResponse
	(*structpb.Struct)(nil),   // 7: google.protobuf.Struct
}
var file_adapters_controllers_grpc_media_proto_depIdxs = []int32{
	7, // 0: grpc.Media.attributes:type_name -> google.protobuf.Struct
	0, // 1: grpc.MediaFiltersParam.order:type_name -> grpc.MediaOrder
	1, // 2: grpc.MediaResponse.media:type_name -> grpc.Media
	1, // 3: grpc.MediaListResponse.media:type_name -> grpc.Media
	2, // 4: grpc.MediaService.GetMediaById:input_type -> grpc.MediaIdParam
	3, // 5: grpc.MediaService.GetMediaByHash:input_type -> grpc.MediaHashParam
	4, // 6: grpc.MediaService.GetMediaList:input_type -> grpc.MediaFiltersParam
	5, // 7: grpc.MediaService.GetMediaById:output_type -> grpc.MediaResponse
	5, // 8: grpc.MediaService.GetMediaByHash:output_type -> grpc.MediaResponse
	6, // 9: grpc.MediaService.GetMediaList:output_type -> grpc.MediaListResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_adapters_controllers_grpc_media_proto_init() }
func file_adapters_controllers_grpc_media_proto_init() {
	if File_adapters_controllers_grpc_media_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_adapters_controllers_grpc_media_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Media); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adapters_controllers_grpc_media_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaIdParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adapters_controllers_grpc_media_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaHashParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adapters_controllers_grpc_media_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaFiltersParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adapters_controllers_grpc_media_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adapters_controllers_grpc_media_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_adapters_controllers_grpc_media_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_adapters_controllers_grpc_media_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adapters_controllers_grpc_media_proto_goTypes,
		DependencyIndexes: file_adapters_controllers_grpc_media_proto_depIdxs,
		EnumInfos:         file_adapters_controllers_grpc_media_proto_enumTypes,
		MessageInfos:      file_adapters_controllers_grpc_media_proto_msgTypes,
	}.Build()
	File_adapters_controllers_grpc_media_proto = out.File
	file_adapters_controllers_grpc_media_proto_rawDesc = nil
	file_adapters_controllers_grpc_media_proto_goTypes = nil
	file_adapters_controllers_grpc_media_proto_depIdxs = nil
}
