// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: adapters/controllers/grpc/media.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MediaServiceClient is the client API for MediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaServiceClient interface {
	GetMediaById(ctx context.Context, in *MediaIdParam, opts ...grpc.CallOption) (*MediaResponse, error)
	GetMediaByHash(ctx context.Context, in *MediaHashParam, opts ...grpc.CallOption) (*MediaResponse, error)
	GetMediaList(ctx context.Context, in *MediaFiltersParam, opts ...grpc.CallOption) (*MediaListResponse, error)
}

type mediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaServiceClient(cc grpc.ClientConnInterface) MediaServiceClient {
	return &mediaServiceClient{cc}
}

func (c *mediaServiceClient) GetMediaById(ctx context.Context, in *MediaIdParam, opts ...grpc.CallOption) (*MediaResponse, error) {
	out := new(MediaResponse)
	err := c.cc.Invoke(ctx, "/grpc.MediaService/GetMediaById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetMediaByHash(ctx context.Context, in *MediaHashParam, opts ...grpc.CallOption) (*MediaResponse, error) {
	out := new(MediaResponse)
	err := c.cc.Invoke(ctx, "/grpc.MediaService/GetMediaByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetMediaList(ctx context.Context, in *MediaFiltersParam, opts ...grpc.CallOption) (*MediaListResponse, error) {
	out := new(MediaListResponse)
	err := c.cc.Invoke(ctx, "/grpc.MediaService/GetMediaList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaServiceServer is the server API for MediaService service.
// All implementations must embed UnimplementedMediaServiceServer
// for forward compatibility
type MediaServiceServer interface {
	GetMediaById(context.Context, *MediaIdParam) (*MediaResponse, error)
	GetMediaByHash(context.Context, *MediaHashParam) (*MediaResponse, error)
	GetMediaList(context.Context, *MediaFiltersParam) (*MediaListResponse, error)
	mustEmbedUnimplementedMediaServiceServer()
}

// UnimplementedMediaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMediaServiceServer struct {
}

func (UnimplementedMediaServiceServer) GetMediaById(context.Context, *MediaIdParam) (*MediaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMediaById not implemented")
}
func (UnimplementedMediaServiceServer) GetMediaByHash(context.Context, *MediaHashParam) (*MediaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMediaByHash not implemented")
}
func (UnimplementedMediaServiceServer) GetMediaList(context.Context, *MediaFiltersParam) (*MediaListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMediaList not implemented")
}
func (UnimplementedMediaServiceServer) mustEmbedUnimplementedMediaServiceServer() {}

// UnsafeMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaServiceServer will
// result in compilation errors.
type UnsafeMediaServiceServer interface {
	mustEmbedUnimplementedMediaServiceServer()
}

func RegisterMediaServiceServer(s grpc.ServiceRegistrar, srv MediaServiceServer) {
	s.RegisterService(&MediaService_ServiceDesc, srv)
}

func _MediaService_GetMediaById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediaIdParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetMediaById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MediaService/GetMediaById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetMediaById(ctx, req.(*MediaIdParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetMediaByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediaHashParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetMediaByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MediaService/GetMediaByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetMediaByHash(ctx, req.(*MediaHashParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetMediaList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediaFiltersParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetMediaList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MediaService/GetMediaList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetMediaList(ctx, req.(*MediaFiltersParam))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaService_ServiceDesc is the grpc.ServiceDesc for MediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.MediaService",
	HandlerType: (*MediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMediaById",
			Handler:    _MediaService_GetMediaById_Handler,
		},
		{
			MethodName: "GetMediaByHash",
			Handler:    _MediaService_GetMediaByHash_Handler,
		},
		{
			MethodName: "GetMediaList",
			Handler:    _MediaService_GetMediaList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adapters/controllers/grpc/media.proto",
}
