name: Robot CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: "Run CI"
    defaults:
      run:
        working-directory: ./robot
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        go: ["1.21.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.10.1
        with:
          go-version: ${{ matrix.go }}
      - name: "Check formatting"
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      - name: "Check unit tests"
        run: make unit-tests
      - name: "Check vet"
        run: make vet
      - name: "Staticcheck linter"
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.5"
          install-go: false
          cache-key: ${{ matrix.go }}
          working-directory: ./robot
